---
- name: Reset Kubernetes Nodes
  hosts: k8s_worker, k8s_master
  become: true

  tasks:
    - name: Reset kubeadm configuration
      shell: |
        kubeadm reset --force
        rm -rf /etc/kubernetes/
        rm -rf /var/lib/kubelet/
        rm -rf /var/lib/etcd/
        rm -rf ~/.kube/
      ignore_errors: yes
      tags: "1"
    
    - name: Prerequest completed rebooting Server and after continue task
      shell: reboot
      async: 1
      poll: 0
      tags: "2"

    - name: Waiting for server back online
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      tags: "3"